### ISSUE TITLE
Add a new category of tests for Processes

### ISSUE THREAD

**Issue by apregier** [genome/wugc-hudson#11]
### Problem:

We want to set up one or more integration tests for Processes that are similar to build tests.  They should run the whole process each time and compare outputs to determine if the test passes.  We would like to use the new test db functionality to make these more robust, although I'm not positive that it is required to make these work.

### Plan:

1. re-import instrument data that is associated with sample TEST-patient1-somval_tumor1 and associate it with a new sample, TEST-patient1-somval_tumor2
2. set up a somatic validation model that is the same as the current somatic validation model test, but with the tumor2 instrument data instead of the tumor1 instrument data.
3. the new trio test will use those two models to generate the trio process.
4. Put those models/builds/samples into the testdb
5. Set up Jenkins to run the process and compare to expected output after the perl tests pass - could run in parallel to model tests.

### Questions for discussion:

How is the Process command stored?

- a) In the genome repo
- b) In the jenkins repo/config

How are the input builds to the process generated/found?  

- a) Always generate on the same code revision as we are testing.  If so, can we reuse the result from the build test, or do we need to generate separately?  This could significantly increase the time of the test, but it would pick up problems in the interface between somatic validation builds and the trio process.
- b) Put one succeeded build in the test db and use that one.  If changes to Somatic Validation happen in a way that make a difference for the Process, we would need to manually update the succeeded build in the test db.

How does jenkins know what to compare to?

- a) Keep a succeeded Process in the test db and have a file in the code that keeps track of which Process is "blessed" for each test
- b) Check in expected output somewhere in the code and always compare to that

**Comment by apregier** [comment]
My answers to the questions:
How is the Process command stored? a
Probably there should be a configuration file for all of the process tests that gives the command and the associated blessed process

How are the input builds to the process generated/found? I keep going back and forth, but I am currently thinking b.  We would miss changes that break the interface, but at some point you can only test so much at once.

How does jenkins know what to compare to? a
I think this will be the easiest way to update expected output - it seems like we should be able to do it with a script to remove the old "blessed" process from the test db and insert a new one.

**Comment by apregier** [comment]
Other questions for discussion: does this plan make sense at all?  What am I missing?

**Comment by tmooney** [comment]
It sounds like we are close to asking for the `X` in `Process : Build :: X : Model`.  (I'm not suggesting we make `Genome::ProcessModel`!)

The existence of both `Build`s and `Process`es should be reconciled eventually.  If we make different decisions here than for the build tests, that might imply we should change the build tests somehow.

**Comment by apregier** [comment]
Agreed - they should be reconciled!  Although I suspect the relationship might be more like Build hasa Process, so the legacy Model-Build relationship might not need to change.

**Comment by apregier** [comment]
In an offline conversation with @jasonwalker80 we discussed using the same standards data that we are using for validation instead of the TEST1 patient.

**Comment by nnutter** [comment]
- How is the Process command stored?
    What is an example command?  Maybe `genome-test-env -d process_integration genome process run my_plan_file.yml`?  `genome-test-env` would make an ephemeral database from the `process_integration` template (database snapshot) and then `genome process run` does its thing.  `my_plan_file.yml` is an input.
- How are the input builds to the process generated/found?
    - I would lean towards b).
    - a) If you want to reuse the result from the model/build test then you would have to share state.  I could add the ability to use an existing ephemeral database to facilitate that but this particular use case hadn't occurred to me before (currently all sharing has to happen after `genome-test-env` is run).
    - b) What changes are you anticipating?  It seems likely any such changes would need to be rolled out via a database migration in which case it should "just work".  Otherwise old Somatic Validation builds would be incompatible for users as well.
- How does jenkins know what to compare to?
    - Either seems reasonable.  Both assert that a human reviewed the output before declaring it good.  Both can couple the expected output to a revision of the code.
- Other comments
    - Alternate wording/ordering of the three questions:
        - What inputs should be used?
        - Run a command.
        - What should the output look like?
    - So this Process is not currently covered by model tests?  And a model test is not a reasonable solution to get coverage?  Analysts currently run `genome process run` by hand?
    - `test-db` only covers GMSchema
        - `test-db` does not necessarily break the "external dependency" on the filesystem.  For file-based inputs (allocations) we probably need some setup to be done to generate them.  I haven't really thought this through yet...
        - `Workflow` is not covered by `test-db`.  I suppose this won't be a problem but it is another "external dependency" we need to eventually decouple.
    - It might be worth writing a script that seeds a database with just the "standards data", i.e. the samples, libraries, and instrument data.  This could become a idealized base for testing.  It may also include default processing profiles and maybe models.

**Comment by apregier** [comment]
> What is an example command?

I am guessing we want to parameterize the final command that is run in jenkins.  So
```
genome-test-env -d process_integration $CMD
```
would be stored in a jenkins script, and then the content of the command would be stored in the code base, perhaps along with a pointer to the correct output to compare to.

$CMD would be:
```
genome variant-reporting wrappers trio --models=cd55282b9dca4d8db8350f281007503e,7718ad01cbe54e2f9c8618396bab778e,216e854d84cf42eea613f1fedf1c94c9 --tumor-sample=H_IJ-NA12878 --followup-sample=H_IJ-NA12878-12-NA12892-87 --normal-sample=H_IJ-NA12892 --coverage-models=5484dc982ade42f69231e4f97c7e0349,81d7f0aaf2294378b7080fe3691bf02a,cd55282b9dca4d8db8350f281007503e,7568ad60d6984dfc930d0de92c92bf92,7718ad01cbe54e2f9c8618396bab778e,cc43b812a799486bac93862fd2cc39cb
```

**Comment by apregier** [comment]
> b) What changes are you anticipating?

I was thinking of changes in what somatic validation builds output or how their output items are accessed.  If somatic validation changes how something is output that a process depends on, we wouldn't catch that interface change.  Hopefully this won't be a big problem in practice!

**Comment by apregier** [comment]
> So this Process is not currently covered by model tests? And a model test is not a reasonable solution to get coverage? Analysts currently run genome process run by hand?

Some of the processes may be run inside models, and in those cases the model test would be sufficient.  However, one specific process (known as "Trio") uses multiple models as inputs, so it doesn't fit well in any existing model test.

**Comment by apregier** [comment]
> It might be worth writing a script that seeds a database with just the "standards data", i.e. the samples, libraries, and instrument data.

We'll also need to include the software results that are outputs of the input somatic validation builds, so pulling them all automatically will actually probably be very useful!

**Comment by nnutter** [comment]
> I am guessing we want to parameterize the final command that is run in jenkins.

Is that because you expect to eventually have multiple Process tests or because you want to be able to tweak each individual run of the tests?

**Comment by apregier** [comment]
> Is that because you expect to eventually have multiple Process tests or because you want to be able to tweak each individual run of the tests?

I do expect to eventually have multiple Process tests (probably sooner rather than later).  But the main reason is so that it is easy to have the inputs and outputs in version control, similar to the "blessed builds" file for the model tests.  I guess it even goes beyond the blessed builds because it would keep all of the information needed to start each process in version control under the genome repo, rather than mixed into the jenkins configuration.

**Comment by susannasiebert** [comment]
For the inputs version control would we only store the values of the inputs or also the contents if they are files (e.g., plan and translations files)?

**Comment by apregier** [comment]
> For the inputs version control would we only store the values of the inputs or also the contents if they are files (e.g., plan and translations files)?

For the trio command, the plan and translation files are resolved by the command before it starts the process.  I am imagining that we would store the command line, which would include model ids and sample ids.

**Comment by susannasiebert** [comment]
Right, for the Trio command that wouldn't really be a problem. I'm thinking more about the generic CreateReport, which is also a process. In this case the command line does include paths to translation and plan files where the contents could change without us noticing if we'd only store the command line. I don't think that we want to test the CreateReport in particular but the potential exist that if we only store the command that any file paths there may be wouldn't have their content under version control.

**Comment by susannasiebert** [comment]
And even with the Trio test the paths to the plan file are somewhat hard-coded and there could be a change to their content that would change the output of the reports without any change to the command line.

**Comment by apregier** [comment]
I see what you are saying with CreateReport.  I guess that command would not be a great candidate for this type of integration test.  We would want things that depend on db entities or on configuration that is in source control.
Trio should be ok because we would just update the "blessed" process at the same time as we update the plan file (because it is in source control)
